title: Sue LEJOG 2016
email: joanna@joannachin.co.uk
description: |
 My 2016 adventure! This isn't an organised event. I'll be cycling the whole 1012 miles and friends will be joining me on some of the legs. Thanks Jon, Karen, Clem, Elizabeth, Holly, Clive, Priya and Jo W for doing some pedalling. Friend Jo Chin will be driving the support vehicle for the whole period in addition to providing emotional support and cups of tea and cake. I'm looking forward to other friends joining as support along the way.
baseurl: ""
url: "http://www.suelejog.com"
twitter_username: DuncombeSue
justgiving: https://www.justgiving.com/SueDuncombeLEJOG
future: true
markdown: kramdown
exclude: ['bower_components', 'node_modules', '.sass-cache', 'gulpfile', 'bower.json', README.md, 'package.json']
